### ISSUE TITLE
2 things

### ISSUE THREAD

**Issue by RobertoMalatesta** [floooh/altai#1]
Hi @floooh,
another nice library from you ?

Two things:

```
robi@pancras:~/src/altai/altai$ tsc
error TS6082: Only 'amd' and 'system' modules are supported alongside --outFile.
```

You can use "system" to avoid this warn/err.
BTW you can target es3 just to catch older browsers.

--R

**Comment by floooh** [comment]
Thanks for the heads up :)

This is all very work in progress, and I'm also still a TypeScript noob. Haven't thought about yet how to make a proper module out of this.

The current version works for me on OSX, typescript has been installed with npm, and I'm editing and testing with Visual Studio Code.

**Comment by RobertoMalatesta** [comment]
:+1:  

These days I'm moving some of my applications to TS (average one being 29'000 lines of code) and I'm really enjoying the ride; VSC is great (I have several stable and nightly tar.gz. versions installed along with different sets of plugins to avoid the few quirks that sometimes pop out).

If you need some help open an issue here and I'll do my best to contribute at least on the TypeScript part.

--R
